

model_training:
  input_shape: [28, 28, 3]
  epochs: 50
  batch_size: 32
  validation_split: 0.2
  learning_rate: 0.001

model_evaluation:
  target_metric: accuracy
  input_shape: [28, 28, 3]
  epochs: 50
  batch_size: 32
  validation_split: 0.2
  learning_rate: 0.001
